# actuator
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
server:
  port: 7777
  http2:
    enabled: true
  undertow:
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true
# nutz
nutz:
  json:
    enabled: true
    mode: compact
    date-format: yyyy-MM-dd HH:mm:ss
  dao:
    sql-template:
      enable: true
      type: beetl
    runtime:
      add-column: true
      basepackage:
      - tech.riemann.nutz.demo.entity
      - BOOT-INF.classes.tech.riemann.nutz.demo.entity
      check-index: true
      create: true
      delete-column: false
      migration: true
    sql-manager:
      paths:
      - sqls
# spring      
spring:
  output:
    ansi:
      enabled: always
  pid:
    fail-on-write-error: true
    file: ${user.home}/${spring.application.name}.pid #pid文件
  servlet:
    multipart: # 文件上传
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: spring-boot-nutz-demo
  datasource:
# 数据源
    druid:
      url: jdbc:mysql://mysql.riemann.tech:13306/thunder?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: thunder
      password: ZhaXcYaabZRKx5zw
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,log4j2
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
      time-between-eviction-runs-millis:  60000
      min-evictable-idle-time-millis:  300000
      validation-query:  SELECT 'ezalor'
      test-while-idle:  true
      test-on-borrow:  true
      test-on-return:  false
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
# 日志配置
logging:  
  file: 
    name: ${user.home}/logs/${spring.application.name}.log
    path: ${user.home}/logs
  level:
    '[org.nutz]': debug
    '[club.zhcs]': debug
    '[tech.riemann]': debug
    '[org.apache.logging]': off
    '[io.swagger]': off
# swagger配置
axe:
  global:
    exception:
      enabled: true
      listener:
        wechat:
          webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8ca09128-8613-4436-9367-e0dc03a17003
springdoc:
  customer:
    theme: feeling-blue
    title: nutz-spring-boot-starter-demo
    url: https://www.riemann.tech
    config-url: /v3/api-docs/swagger-config
  server:
    url: http://localhost:7777
    description: nutz-spring-boot-starter-demo
  info:
    title: nutz-spring-boot-starter-demo
    description: nutz-spring-boot-starter-demo API接口文档
    version: 1.0.0
    terms-of-service: https://github.com/nutzam/nutz-spring-boot-starter
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0
    contact:
      email: product@ipmt.online
      name: nutz-spring-boot-starter-demo
      url: https://www.riemann.tech
  swagger-ui:
    enabled: true
  group-configs:
  - group: default
    packages-to-scan:
    - tech.riemann.nutz.demo.controller
  api-docs:
    enabled: true
    groups:
      enabled: true
wx:
  miniapp:
    appid: wxdd12f1e5067bb20b
    secret: 526c34f3a2842082abfd36509639335c
  mp:
    app-id: wx6e4f32b9bfd64693
    secret: 7ec96826e905841e4912e8acdf5037ed
wechat:
  oauth:
    mp:
      domain: poly.ngrok.kerbores.com
      router: /wechat/login
    pc:
      domain: poly.ngrok.kerbores.com
      router: /wechat/login/qr