# actuator
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
# server
server:
  port: 8888
  http2:
    enabled: true
  undertow:
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true
# nutz
nutz:
  json:
    enabled: true
    mode: compact
  dao:
    sql-template:
      enable: true
      type: beetl
    runtime:
      add-column: true
      basepackage:
      - tech.riemann.demo.entity
      check-index: true
      create: true
      delete-column: false
      migration: true
    sql-manager:
      paths:
      - sqls
# spring      
spring:
  output:
    ansi:
      enabled: always
  pid:
    fail-on-write-error: true
    file: ${user.home}/${spring.application.name}.pid #pid文件
  servlet:
    multipart: # 文件上传
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: spring-boot-nutz-demo
  datasource:
# 数据源
    druid:
      url: jdbc:mysql://gitea.kerbores.com:3306/thunder?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: developer
      password: G00dl^ck
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,log4j2
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
      time-between-eviction-runs-millis:  60000
      min-evictable-idle-time-millis:  300000
      validation-query:  SELECT 'ezalor'
      test-while-idle:  true
      test-on-borrow:  true
      test-on-return:  false
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true# 日志配置
logging:  
  file: 
    name: ${user.home}/logs/${spring.application.name}.log
    path: ${user.home}/logs
  level:
    '[org.nutz]': debug
    '[club.zhcs]': debug
    '[tech.riemann]': debug
    '[org.apache.logging]': off
    '[io.swagger]': off
# swagger配置
axe:
  global:
    exception:
      enabled: true
  swagger:
    docket:      auth: 
        base-package: tech.riemann.demo.controller.auth
        description: 登录认证模块
        title: Auth
      acl: 
        base-package: tech.riemann.demo.controller.acl
        description: Access Control Label 访问控制模块
        title: ACL
      dictionary: 
        base-package: tech.riemann.demo.controller.dictionary
        description: 统一数据字典管理模块
        title: 数据字典
      all: 
        base-package: tech.riemann.demo.controller
    customer:
      logo: http://image.kerbores.com/xsj/icon.png
      title: NUTZ项目示例
      url: https://www.riemann.tech/
    title: ${spring.application.name}
    description: 基于nutz的项目示例
    
    version: 1.0
    contact:
      email: kerbores@gmail.com
      name: Kerbores
      url: https://www.riemann.tech/
    authorization:
      key-name: Authorization