server:
  port: 8080
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
swagger:
  base-package: org.nutz.demo
  title: nutz-spring-boot-starter-demo
  description: nutz-spring-boot-starter-demo swagger 接口手册示例
  authorization:
    key-name: Authorization
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: spring-boot-nutz-starter-demo
  datasource:
    druid:
      url:  jdbc:sqlite::resource:sqlite/demo.db
      username: root
      password: G00dl^ck
      driver-class-name: org.sqlite.JDBC
      filters: stat,log4j2
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
      time-between-eviction-runs-millis:  60000
      min-evictable-idle-time-millis:  300000
      validation-query:  SELECT '1'
      test-while-idle:  true
      test-on-borrow:  true
      test-on-return:  false
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
  config:
    location: null
logging:
  file:
    path: ${user.home}/log/
    name: ${user.home}/log/${spring.application.name}.log
  level:
    org.nutz: debug
    springfox: off
    io.swagger: off
nutz:
  ngrok:
    port: 8080
    token: abcdef
  json:
    enabled: true
    mode: compact
    ignore-null: true
    compact: true
    date-format: yyyy-MM-dd Hh:mm:ss
  dao:
    sql-template:
      enable: true
      type: beetl
    sql-manager:
      mode: file #自定义sql管理模式 file和xml
      paths: # 自定义sql文件路径
      - sqls
    runtime:
      create: true #是否自动建表
      migration: true #是否自动变更
      add-column: true # 是否添加列
      delete-column: true # 是否删除列
      foce-create: false # 是否删表重建，注意此功能会删除全部表及数据，一般应用于demo或测试
      check-index: true # 是否检查索引
      basepackage: # 相关实体所在包
      - org.nutz.demo.bean
