management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
nutz:
  json:
    enabled: true
    mode: compact
  dao:
    runtime:
      add-column: true
      basepackage:
      - club.zhcs.nutz.demo.entity
      check-index: false
      create: true
      delete-column: true
      migration: true
    sql-manager:
      paths:
      - sqls
server:
  port: 8889
spring:
  output:
    ansi:
      enabled: always
  pid:
    fail-on-write-error: true
    file: ${user.home}/${spring.application.name}.pid
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: nutz-spring-boot-starter-demo
  datasource:
    druid:
      url: jdbc:mysql://www.emasapple.cn:3306/thunder?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: G00dl^ck
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:postgresql://10.0.0.174:5432/thunder
#      username: postgres
#      password: G00dl^ck
#      driver-class-name: org.postgresql.Driver
      filters: stat,wall,log4j2
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
      time-between-eviction-runs-millis:  60000
      min-evictable-idle-time-millis:  300000
      validation-query:  SELECT 'nutz'
      test-while-idle:  true
      test-on-borrow:  true
      test-on-return:  false
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
axe:
  swagger: 
    title: nutz-spring-boot-starter-demo
    description: nutz-spring-boot-starter-demo swagger 接口手册示例
    contact:
      name: Kerbores
      email: kerbores@gmail.com
      url: https://github.com/kerbores
    authorization:
      key-name: Authorization
    docket:
      acl: 
        base-package: club.zhcs.nutz.demo.controller.acl
        contact:
          email: kerbores@gmail.com
          name: Kerbores
          url: https://www.kerbores.com
        description: 访问控制
        title: ACL
        version: 1.0.0
      code: 
        base-package: club.zhcs.nutz.demo.controller.code
        contact:
          email: kerbores@zhcs.club
          name: ZHCS
          url: https://www.zhcs.club
        description: 通用码表
        title: Code book
        version: 1.1.0
logging:  
  file: 
    name: ${user.home}/logs/${spring.application.name}.log
    path: ${user.home}/logs
  level:
    '[org.nutz]': debug
    '[club.zhcs.nutz.demo]': debug
    '[org.apache.logging]': off
    springfox: off
    '[io.swagger]': off
