server:
  port: 8080
management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'
swagger:
  base-package: org.nutz.demo
  title: nutz-spring-boot-starter-demo
  description: nutz-spring-boot-starter-demo swagger 接口手册示例
  authorization:
    key-name: Authorization
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: spring-boot-nutz-starter-demo
  datasource:
    druid:
      url:  jdbc:sqlite:${user.home}/demo.db
      username: root
      password: G00dl^ck
      driver-class-name: org.sqlite.JDBC
      filters: stat,log4j2
      initial-size: 10
      min-idle:  1
      max-active:  50
      max-wait:  60000
      time-between-eviction-runs-millis:  60000
      min-evictable-idle-time-millis:  300000
      validation-query:  SELECT '1'
      test-while-idle:  true
      test-on-borrow:  true
      test-on-return:  false
      pool-prepared-statements:  false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
  config:
    location: null
logging:
  file:
    path: ${user.home}/log/
    name: ${user.home}/log/${spring.application.name}.log
  level:
    org.nutz: debug
    springfox: off
    io.swagger: off
nutz:
  ngrok:
    port: 8080
    token: 2lu19cqqf2hciq1hoti37uvjo2
  json:
    enabled: true
    mode: compact
    ignore-null: true
    compact: true
    date-format: yyyy-MM-dd Hh:mm:ss
  dao:
    sql-template:
      enable: true
      type: beetl
    sql-manager:
      paths: 
      - sqls
    runtime:
      create: true 
      migration: true 
      add-column: true 
      delete-column: true 
      foce-create: false 
      check-index: false
      basepackage: 
      - org.nutz.demo.bean
