export default [
  {
    type: "input",
    field: "key",
    title: "操作Key",
    info: "",
    props: {
      type: "text",
      minlength: 3,
      maxlength: 10,
      placeholder: "请输入操作key",
      clearable: true,
    },
    _fc_drag_tag: "input",
    hidden: false,
    display: true,
    validate: [
      {
        trigger: "change",
        mode: "required",
        message: "请输入操作key",
        required: true,
        type: "string",
      },
      {
        trigger: "change",
        mode: "min",
        message: "操作key不少于3个字符",
        min: 3,
        type: "string",
      },
    ],
  },
  {
    type: "input",
    field: "name",
    title: "操作名",
    info: "",
    props: {
      type: "text",
      maxlength: 50,
      minlength: 2,
      placeholder: "请输入操作名",
      clearable: true,
      showPassword: true,
    },
    _fc_drag_tag: "input",
    hidden: false,
    display: true,
    validate: [
      {
        trigger: "change",
        mode: "required",
        message: "请输入操作名",
        required: true,
        type: "string",
      },
      {
        trigger: "change",
        mode: "min",
        message: "操作名长度在 2 到 50 个字符",
        min: 2,
        type: "string",
      },
      {
        trigger: "change",
        mode: "max",
        message: "操作名长度在 2 到 50 个字符",
        max: 50,
        type: "string",
      },
    ],
  },
];
